# Generated by Django 4.0.6 on 2022-07-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_alter_photo_options_photo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='text',
            field=models.CharField(default='default text', max_length=60),
            preserve_default=False,
        ),
    ]
