# Generated by Django 4.0.6 on 2022-07-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_photo_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
